### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by pachacamac** [thebrianemory/corneal#5]
Hey nice project! :) 

One question: Is there a baked in way to create new migrations for e.g. adding fields to a model or something like this?

**Comment by thebrianemory** [comment]
Hi Marc,

Thank you! :)

There is currently not a way to do that using Corneal. If you are using [`sinatra-activerecord`](https://github.com/janko-m/sinatra-activerecord), you can create a migration with `rake db:create_migration NAME=create_users`. This will create your empty migration file to make any changes you would like.
```
class CreateUsers < ActiveRecord::Migration
  def change
  end
end
```

**Comment by pachacamac** [comment]
thanks good to know :)
