### ISSUE TITLE
[New feature idea] Api Only generator

### ISSUE THREAD

**Issue by marek2901** [thebrianemory/corneal#6]
Hello,

I was wondering if corneal could generate api only controllers and scaffolds. 

I would be happy to make a contribution to this repo, though I want to gather some specifications at first. So, there is my proposition:

- Use grape as API engine, allow user to specify --api-only flag while running app generator.
- Use strategy write api-controller and api-scaffold generator, so user can input `corneal api-controller` or `corneal api-scaffold`.
- NOTE I would like to throw en error if `api-*` generator is called without prior --api-only flag called during app generation

Let me know what you Think. During the weekend I should get some spare time so I'll prepare some Pull Request :)

**Comment by thebrianemory** [comment]
Hello,

If you feel like an API generator would be useful for those that use Sinatra regularly, your PR would be most welcome. :)
