### ISSUE TITLE
Possible Runtime Bug

### ISSUE THREAD

**Issue by Kiveo** [thebrianemory/corneal#8]
I suspect there may be a bug where generating a scaffold scheme like airplane, will cause an uninitialized constant ApplicationController error upon trying rake or shotgun.  My random hunch was that Ai comes alphabetically before Ap (airplane vs application controller). User scaffold worked fine. Thus, I suspect naming a controller won’t work well unless it’s alphabetically after application controller. It may have nothing to do with corneal but this is what I used to generate a file structure and thought to comment about it. 

I used a different name, and had success.

**Comment by odineiramone** [comment]
Hello @Kiveo!

The `require_all` gem require files in alphabetical order ([source](https://github.com/jarmo/require_all#usage)). It causes the `airplane_controller.rb` (for example) be required before the `application_controller.rb`.

I solve this requiring the `application_controller.rb` before the `require_all 'app'` on `environment.rb` file:

```ruby
# environment.rb

# some configuration stuff...

require './app/controllers/application_controller'
require_all 'app'
```

@thebrianemory, can I open a pull-request adding this at the corneal's generators?

**Comment by thebrianemory** [comment]
@odineiramone Absolutely!

**Comment by odineiramone** [comment]
Made a pull-request #10

**Comment by thebrianemory** [comment]
Merged and upgraded on RubyGems. Thank you @odineiramone!
