### ISSUE TITLE
scaffold problem

### ISSUE THREAD

**Issue by garalo** [thebrianemory/corneal#9]
corneal scaffold test_model
      create  app/models/test_model.rb
Traceback (most recent call last):
        25: from /home/akali/.rbenv/versions/2.5.1/bin/corneal:23:in `<main>'
        24: from /home/akali/.rbenv/versions/2.5.1/bin/corneal:23:in `load'
        23: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/corneal-1.2.1/bin/corneal:6:in `<top (required)>'
        22: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        21: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        20: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        19: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        18: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:40:in `block in register'
        17: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
        16: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
        15: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
        14: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
        13: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
        12: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        11: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        10: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         9: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/corneal-1.2.1/lib/corneal/generators/scaffold/scaffold_generator.rb:14:in `create_model'
         8: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
         7: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
         6: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
         5: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
         4: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         3: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         2: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/corneal-1.2.1/lib/corneal/generators/model/model_generator.rb:46:in `create_migration'
         1: from /home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/corneal-1.2.1/lib/corneal/generators/model/model_generator.rb:46:in `entries'
/home/akali/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/corneal-1.2.1/lib/corneal/generators/model/model_generator.rb:46:in `open': No such file or directory @ dir_initialize - db/migrate (Errno::ENOENT)

**Comment by odineiramone** [comment]
Hello @garalo! For any reason you don't have the `db/migrate` folder in the default location (the default location is the root folder of your app).

Create a folder named `migrate` under `db` folder should work. If it don't work, try to generate a new app with `corneal new APP-NAME` and do the scaffold again.

If you receive this error again, please, open an issue with as much detail as you can.

Thanks! 😄

**Comment by odineiramone** [comment]
@thebrianemory, can we close this issue?

**Comment by thebrianemory** [comment]
Sure thing. Thanks for the help @odineiramone!
